# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      CATALINA_HOME: C:\Program Files\Apache Software Foundation\Tomcat 8.5
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0_281
    
    steps:
    
      - name: Step-1 Checkout the code
        uses: actions/checkout@v2
      
        
     # - name: Move file
      #  run: echo Y | XCOPY C:\GitHub_Actions\Contrast\Self_Hosted\Workspace\Contrast_Security\Contrast_Security\startup-tomcat-contrast.bat C:\ProgramData\Contrast\java
        #echo "No" | copy/-Y c:\source c:\Dest\
        
      #Running bat  
      - name: Run a bat file 
       # if: ${{ env.CATALINA_HOME == 'C:\ProgramData\Contrast\java\apache-tomcat-9.0.43\apache-tomcat-9.0.43' }}
        run: |
               .\startup-tomcat-contrast.bat
             
      - name: Check 
        run: echo "Done"
        
      - name: Step-4 Zip the Source code
        uses: papeloto/action-zip@v1
        with:
          dest: BatFile.zip
          
  #Verify the Zip folder
      - name: Step-5 Verify Directory
        run: dir
      
  #Move the Zip to D: drive
      - name: Step-6 Move Directory to D drive
        run: move BatFile.zip D:\Actions
